# Generated by Django 3.2.9 on 2021-12-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name_plural': 'Stocks'},
        ),
    ]
